---
# Create namespace for ibm wazi devspaces
# tasks file for devspaces
- include_vars: wazi-devspaces3.yml

- name: "Create ansible-workspace directory - IBM Wazi for DevSpaces"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/ansible-workspace/wazi-devspace/generated_yamls"
    state: directory

- name: "Create subscription.yaml file - IBM Wazi for DevSpaces"
  ansible.builtin.template:
    src: files/wazi-devspaces-subscription.yaml.j2
    dest: "{{ playbook_dir }}/ansible-workspace/wazi-devspace/generated_yamls/wazi-devspaces-subscription.yaml"

- name: "Create IBM Wazi for DevSpaces Subscription with Native YAML API"
  kubernetes.core.k8s:
    state: present
    namespace: "openshift-operators"
    src: "{{ playbook_dir }}/ansible-workspace/wazi-devspace/generated_yamls/wazi-devspaces-subscription.yaml"

#install IBM Wazi for DevSpaces in openshift-operators namespace to install by default on all namespaces
- name: "Retrieve IBM Wazi for DevSpaces subscription info"
  kubernetes.core.k8s_info:
    kind: Subscription
    namespace: "openshift-operators"
    name: "{{ devspaces_subscription.name }}"
    api_version: "{{ devspaces_subscription.apiVersion }}"
  register: devspaces_subscription_info
  until:
    - "devspaces_subscription_info.resources is defined and devspaces_subscription_info.resources | length > 0"
    - "'state' in devspaces_subscription_info.resources[0].status and devspaces_subscription_info.resources[0].status.state == 'AtLatestKnown'"
  retries: 30
  delay: 30

- name: "Verify IBM Wazi for devspaces subscription: '{{ devspaces_subscription.name }}'"
  ansible.builtin.assert:
    that:
      - devspaces_subscription_info.resources[0].metadata.creationTimestamp != ""
      - devspaces_subscription_info.resources[0].status.installplan.kind == "InstallPlan"
      - devspaces_subscription_info.resources[0].status.installplan.name != ""
      - devspaces_subscription_info.resources[0].status.state == "AtLatestKnown"
      - devspaces_subscription_info.resources[0].status.conditions[0].reason == "AllCatalogSourcesHealthy"

- name: "Create license.yaml - IBM Wazi for DevSpaces"
  ansible.builtin.template:
    src: files/wazi-license.yaml.j2
    dest: "{{ playbook_dir }}/ansible-workspace/wazi-devspace/generated_yamls/wazi-license.yaml"

- name: "Accept wazi DevSpaces License with Native YAML API - IBM Wazi for DevSpaces"
  kubernetes.core.k8s:
    state: present
    namespace: "openshift-operators"
    src: "{{ playbook_dir }}/ansible-workspace/wazi-devspace/generated_yamls/wazi-license.yaml"

# Wait for 50 secconds until wazi license is up (status block unavailable for verification)
- name: Wait for 50sec for wazi License setup
  pause:
    seconds: 50

- name: "Create IBM Wazi for DevSpaces che cluster with Native YAML API"
  kubernetes.core.k8s:
    state: present
    namespace: "openshift-operators"
    src: "files/wazi-devspaces3.yaml"

# tasks to verify the installation
- name: "Retrieve IBM Wazi for DevSpaces custom resource instance Info"
  kubernetes.core.k8s_info:
    namespace: "openshift-operators"
    kind: "{{ devspaces.kind }}"
    name: "{{ devspaces.name }}"
    api_version: "{{ devspaces.apiVersion }}"
  register: devspaces_info
  until:
    - "devspaces_info.resources is defined and devspaces_info.resources | length > 0"
    - "devspaces_info.resources[0].status is defined and devspaces_info.resources[0].status | length > 0"
    - "'chePhase' in devspaces_info.resources[0].status and devspaces_info.resources[0].status.chePhase == 'Active'"
    - "'gatewayPhase' in devspaces_info.resources[0].status and devspaces_info.resources[0].status.gatewayPhase == 'Established'"
  retries: 30
  delay: 50

- ansible.builtin.debug:
        var: devspaces_info

- name: "Verify IBM Wazi for Devspaces: '{{ devspaces.name }}'"
  ansible.builtin.assert:
    that:
      - devspaces_info.resources[0].status.chePhase == "Active"
      - devspaces_info.resources[0].status.gatewayPhase == "Established"
      - devspaces_info.resources[0].status.cheURL | length > 0

- name: "Jinja Conversion for Devspaces Project Yaml"
  ansible.builtin.template:
    src: "files/devspaces-project.yaml"
    dest: "{{ GIT_CLONE_DIR }}/ocp/ansible/roles/wazi-devspaces/files/devspaces-project.yaml"
    mode: '0644'

- name: "Create project with Native YAML API for Devspaces"
  kubernetes.core.k8s:
    state: present
    src: "files/devspaces-project.yaml"

- name: "Create Devworkspace Template for z/OS Connect Designer with Native YAML API"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ openshift_username }}-devspaces"
    src: "files/devworkspace-template.yaml"

- name: "Create Devworkspace for z/OS Connect Designer with Native YAML API"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ openshift_username }}-devspaces"
    src: "files/devworkspace.yaml"

- name: "Retrieve DevWorkspace instance info"
  kubernetes.core.k8s_info:
    namespace: "{{ openshift_username }}-devspaces"
    kind: "{{ devworkspace.kind }}"
    name: "{{ devworkspace.name }}"
    api_version: "{{ devworkspace.apiVersion }}"
  register: devworkspace_info
  until:
    - "devworkspace_info.resources is defined and devworkspace_info.resources | length > 0"
    - "devworkspace_info.resources[0].status is defined and devworkspace_info.resources[0].status | length > 0"
    - "'phase' in devworkspace_info.resources[0].status and devworkspace_info.resources[0].status.phase == 'Running'"
  retries: 30
  delay: 10

- name: "Verify DevWorkspace"
  ansible.builtin.assert:
    that:
      - devworkspace_info.resources[0].status.phase == "Running"
