apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: zmodstack-deploy
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/IBM/zmodstack-deploy.git'
        - name: revision
          value: tekton
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: zmodstack-deploy
    - name: ansible-runner
      params:
        - name: project-dir
          value: ocp/tekton
        - name: args
          value:
            - '--help'
        - name: user-home
          value: /tekton/home
        - name: image
          value: 'quay.io/ansible/ansible-runner:stable-2.12-latest'
      taskRef:
        kind: Task
        name: ansible-runner
      workspaces:
        - name: runner-dir
          workspace: zmodstack-deploy
  workspaces:
    - name: zmodstack-deploy
