apiVersion: v1
baseDomain: {{ DNS_ZONE_NAME }}
compute:
- hyperthreading: Enabled
  name: worker
  platform: 
    azure:
      type: {{ COMPUTE_VM_SIZE }}
      osDisk:
        diskSizeGB: {{ COMPUTE_DISK_SIZE }}
        diskType: {{ COMPUTE_DISK_TYPE }}
      zones:
      - '1'
      - '2'
      - '3'
  replicas: {{ COMPUTE_INSTANCE_COUNT }}
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: 
    azure:
      type: {{ CONTROL_PLANE_VM_SIZE }}
      osDisk:
        diskSizeGB: {{ CONTROL_PLANE_DISK_SIZE }}
        diskType: {{ CONTROL_PLANE_DISK_TYPE }}
      zones:
      - '1'
      - '2'
      - '3'
  replicas: {{ CONTROLPLANE_INSTANCE_COUNT }}
metadata:
  creationTimestamp: null
  name: {{ CLUSTER_NAME }}
networking:
  clusterNetwork:
  - cidr: {{ CLUSTER_NETWORK_CIDR }}
    hostPrefix: {{ HOST_ADDRESS_PREFIX }}
  machineCIDR: {{ VIRTUAL_NETWORK_CIDR }}
  networkType: OpenShiftSDN
  serviceNetwork:
  - {{ SERVICE_NETWORK_CIDR }}
platform:
  azure:
    baseDomainResourceGroupName: {{ DNS_ZONE_RESOURCE_GROUP }}
    region: {{ LOCATION }}
    networkResourceGroupName: {{ NETWORK_RESOURCE_GROUP }}
    virtualNetwork: {{ VIRTUAL_NETWORK_NAME }}
    controlPlaneSubnet: {{ CONTROL_PLANE_SUBNET_NAME }}
    computeSubnet: {{ COMPUTE_SUBNET_NAME }}
    outboundType: {{ OUTBOUND_TYPE }}
    resourceGroupName: {{ CLUSTER_RESOURCE_GROUP_NAME }}
pullSecret: '{{ PULL_SECRET }}'
fips: {{ ENABLE_FIPS }}
publish: {{ PRIVATE_OR_PUBLIC }}
sshKey: |
  {{ BOOTSTRAP_SSH_PUBLIC_KEY }}