---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-zmodstack-deploy-cluster-role-binding-1
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ibm-zmodstack-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-zmodstack-deploy-cluster-role-1
