---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-zmodstack-deploy-cluster-role-1
rules:
  - apiGroups:
      - project.openshift.io
    resources:
      - projectrequests
    verbs:
      - create
