---
kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: zoscb-install-pipeline
spec:
  tasks:
    - name: git-clone-zmodstack
      params:
        - name: url
          value: 'https://github.com/IBM/zmodstack-deploy.git'
        - name: revision
          value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: zmodstack-ws
    - name: zoscb-install
      params:
        - name: project-dir
          value: ocp/ansible
        - name: ansible-command
          value: ansible-playbook playbooks/zoscb-install.yaml
      runAfter:
        - git-clone-zmodstack
      taskRef:
        kind: Task
        name: ansible
      workspaces:
        - name: ws
          workspace: zmodstack-ws
  workspaces:
    - name: zmodstack-ws