---
kind: ZosCloudBroker
apiVersion: zoscb.ibm.com/v2beta1
metadata:
  name: zoscloudbroker
spec:
  license:
    accept: true
  multiNamespace: false
  logLevel: debug
  galaxyConfig:
    enabled: true
    galaxyURL: 'https://galaxy.ansible.com'
  storage:
    configure: false
    enabled: true
    pvc: zoscloudbroker
    size: 5Gi
    volumeMode: Filesystem
  managerResources: {}
  catalogResources: {}
  uiResources: {}