---
kind: "ZosCloudBroker"
apiVersion: "zoscb.ibm.com/v2beta1"
metadata:
  name: "zoscloudbroker"
spec:
  catalogResources: {}
  galaxyConfig:
    enabled: true
    galaxyURL: 'https://galaxy.ansible.com'
  license:
    accept: true
  logLevel: debug
  managerResources: {}
  storage:
    accessModes: ReadWriteMany
    configure: true
    enabled: false
    size: 5Gi
    storageClassName: {{ current_default_sc }}
    volumeMode: Filesystem
  uiResources: {}