---
kind: PersistentVolumeClaim
apiVersion: "v1"
metadata:
  name: "zoscloudbroker"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
  volumeMode: "Filesystem"
  storageClassName: gp3-immediate