kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-zoscb-admin-test
  namespace: demo-js
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ibm-zmodstack-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
