---
- name: Deploy OCP Cluster
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
  - name: Setup OCP Cluster
    ansible.builtin.include_role:
      name: "ocpcluster"
    tags: "ocpcluster"