---
- name: Pre Deploy Installations
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
  - name: Update Packages and Installing Package Dependencies
    ansible.builtin.shell: dnf update -y
  - name: Install Azure CLI
    ansible.builtin.shell: |
      rpm --import https://packages.microsoft.com/keys/microsoft.asc
      dnf install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm
      dnf install -y azure-cli
  - name: Install jq
    ansible.builtin.shell: dnf install -y jq
  - name: Install podman
    ansible.builtin.shell: yum install -y podman
  - name: Install httpd-tools
    ansible.builtin.shell: yum install -y httpd-tools
  - name: Install Ansible Dependencies
    ansible.builtin.shell: |
      ansible-galaxy collection install kubernetes.core
      ansible-galaxy collection install cloud.common
      pip3 install --ignore-installed PyYAML
      pip3 install kubernetes
      pip3 install openshift 