---
- name: Deploy and configure an e2e zmodstack demo environment
  hosts: localhost
  # gather_facts: false
  tasks:
    - name: Run the Wazi-aaS role to create an instance
      ansible.builtin.import_role:
        name: "wazi-aas"
      vars:
        action: create
      tags:
        - create

- name: Check Ansible connection to new VSI
  hosts: new_vsi
  gather_facts: False
  tasks:
    - name: Wait for VSI to become reachable over SSH
      ansible.builtin.wait_for_connection:
        connect_timeout: 10
        delay: 3
        timeout: 40