---
- name: Deploy and configure an e2e zmodstack demo environment
  hosts: localhost
  # gather_facts: false
  tasks:
    - name: Check for and create Secret if necessary
      ansible.builtin.import_role:
        name: ocp
      tags:
        - ssh

    - name: Run the Wazi-aaS role to create an instance
      ansible.builtin.import_role:
        name: "wazi-aas"
      vars:
        action: create
      tags:
        - create

    # - name: Run the Wazi-aaS role to delete an instance
    #   ansible.builtin.import_role:
    #     name: "wazi-aas"
    #   vars:
    #     action: delete
    #   tags:
    #     - delete

    - name: Create z/OS Cloud Broker ZosEndpoint CR
      ansible.builtin.import_role:
        name: "zoscb"
        tasks_from: zosendpoint
      tags:
        - zoscb

    - name: Create z/OS Cloud Broker OperatorCollection CR
      ansible.builtin.import_role:
        name: "zoscb"
        tasks_from: operatorcollection
      tags:
        - zoscb
    
    - name: Create z/OS Cloud Broker Credential 
      ansible.builtin.import_role:
        name: "zoscb"
        tasks_from: secret
      tags:
        - zoscb

    - name: Create z/OS Cloud Broker SuboperatorConfig CR
      ansible.builtin.import_role:
        name: "zoscb"
        tasks_from: suboperatorconfig
      tags:
        - zoscb
