###############################################################################
# © Copyright IBM Corporation 2022
###############################################################################

---
- name: Deploy IBM ZmodStack
  hosts: localhost
  become: false
  collections:
    - ibm.ibm_zos_core
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  gather_facts: false
  pre_tasks:
    - name: Retrieve the default storage class
      ansible.builtin.command: oc get sc
      register: sc_output

    - name: Filter default storage class
      ansible.builtin.command: grep "(default)"
      args:
        stdin: "{{ sc_output.stdout }}"
      register: filtered_sc_output

    - name: Extract default storage class name
      ansible.builtin.set_fact:
        current_default_sc: "{{ filtered_sc_output.stdout_lines[0].split()[0] }}"
  
  tasks:
    # ****************************************************************************************************************************
    # *
    # *  Playbook section for creating all ZmodSTack resources
    # *
    # ****************************************************************************************************************************
    
    # ****************************************************************************************************************************
    # *
    # Install IBM z/OS Connect
    # *
    # ****************************************************************************************************************************

    # Dynamically INCLUDE ansible role
    - name: Include z/OS Dev Install role/task tagged for z/OS Connect Operator, Designer, server image
      ansible.builtin.include_role:
        name: "zosconnect"
      when: zosconnect | bool

    # ****************************************************************************************************************************
    # *
    # Install IBM Wazi for Dev Spaces
    # *
    # ****************************************************************************************************************************

    # Dynamically INCLUDE ansible role
    - name: Include z/OS Dev Install role/task tagged for Red Hat Dev Spaces
      ansible.builtin.include_role:
        name: "wazi-devspaces"
        tasks_from: "{{ 'wazi-devspaces3.yaml' if wazidevspacesversion== '3.x' else 'wazi-devspaces2.yaml' }}"
      when: wazidevspaces | bool

    # ****************************************************************************************************************************
    # *
    # Install IBM z/OS Cloud Broker
    # *
    # ****************************************************************************************************************************

    - name: Deploy IBM z/OS Cloud and Modenization Stack - Openshift z/OS Cloud Broker Operator
      block:
        # Dynamically INCLUDE ansible role
        - name: Include z/OS Dev Install role/task tagged for z/OS Cloud Broker
          ansible.builtin.include_role:
            name: "zoscb"
          when: zoscb | bool