###############################################################################
# © Copyright IBM Corporation 2022
###############################################################################

---
- name: Deploy IBM ZmodStack on AWS
  hosts: localhost
  become: false
  collections:
    - ibm.ibm_zos_core
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  gather_facts: false

  tasks:
    # ****************************************************************************************************************************
    # *
    # *  Playbook section for creating all ZmodSTack resources on AWS
    # *
    # ****************************************************************************************************************************
 
    - name: Deploy IBM z/OS Cloud and Modenization Stack - Openshift z/OS Cloud Broker Operator
      block:
        # ****************************************************************************************************************************
        # *
        # Install IBM z/OS Cloud Broker
        # *
        # ****************************************************************************************************************************

        # Dynamically INCLUDE ansible role
        - name: Include z/OS Dev Install role/task tagged for z/OS Cloud Broker
          ansible.builtin.include_role:
            name: "zoscb"
          when: zoscb | bool

    # ****************************************************************************************************************************
    # *
    # Install IBM z/OS Connect
    # *
    # ****************************************************************************************************************************

    # Dynamically INCLUDE ansible role
    - name: Include z/OS Dev Install role/task tagged for z/OS Connect Operator, Designer, server image
      ansible.builtin.include_role:
        name: "zosconnect"
      when: zosconnect | bool

    # ****************************************************************************************************************************
    # *
    # Install IBM Wazi for Dev Spaces
    # *
    # ****************************************************************************************************************************

    # Dynamically INCLUDE ansible role
    - name: Include z/OS Dev Install role/task tagged for Red Hat Dev Spaces
      ansible.builtin.include_role:
        name: "wazi-devspaces"
        tasks_from: "{{ 'wazi-devspaces3.yaml' if wazidevspacesversion== '3.0.0' else 'wazi-devspaces2.yaml' }}"
      when: wazidevspaces | bool
