---
- name: Deploy IBM Z and Cloud Modernization Stack
  hosts: localhost
  gather_facts: false
  vars:
    # ansible_python_interpreter: /usr/bin/python3
    zosconnect: false
    wazidevspaces: false
    zoscb: true

  tasks:
    - name: Deploy IBM z/OS Connect
      ansible.builtin.include_role:
        name: "zosconnect"
      when: zosconnect | bool

    - name: Deploy IBM Wazi Dev Spaces
      ansible.builtin.include_role:
        name: "wazi-devspaces"
        tasks_from: "{{ 'wazi-devspaces3.yaml' if wazidevspacesversion == '3.x' else 'wazi-devspaces2.yaml' }}"
      when: wazidevspaces | bool

    - name: Deploy IBM z/OS Cloud Broker
      ansible.builtin.include_role:
        name: "zoscb"
      when: zoscb | bool
