###############################################################################
# © Copyright IBM Corporation 2022
###############################################################################

---
- name: Deploy IBM ZmodStack
  hosts: localhost
  become: false
  collections:
    - ibm.ibm_zos_core
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  gather_facts: false

  tasks:
    # ****************************************************************************************************************************
    # *
    # *  Playbook section for creating RedHat OpenShift Cluster
    # *
    # ****************************************************************************************************************************
    - name: Deploy RedHat Openshift Cluster
      block:
        # Dynamically INCLUDE ansible role
        - name: Include ocp-install role/task tagged for Creating the RedHat OpenShift Cluster
          ansible.builtin.include_role:
            name: "ocp-install"

        - name: Include autoscaler role/task tagged for Creating the Autoscaler for RedHat OpenShift Cluster
          ansible.builtin.include_role:
            name: "autoscaler"
          when: autoscaler | bool