---
- name: Fetch OpenShift Logs
  hosts: all
  gather_facts: no
  vars_files:
    - vars/extra_vars.yml
  vars:
    - date_time_stamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"  
  tasks:
  - name: Copy OpenShift Install log to home directory in Bootstrap VM
    ansible.builtin.copy:
      src: /mnt/openshift/openshiftfourx/.openshift_install.log
      dest: ~/openshift_install.log
      remote_src: yes
    ignore_errors: true   
  - name: Copy Handler log to home directory in Bootstrap VM
    ansible.builtin.copy:
      src: /var/log/azure/custom-script/handler.log
      dest: ~/handler.log
      remote_src: yes
    ignore_errors: true   
  - name: Copy Bootstrap script to home directory in Bootstrap VM
    ansible.builtin.copy:
      src: /var/lib/waagent/custom-script/download/0/bootstrap.sh
      dest: "/home/{{ ansible_ssh_user }}/bootstrap.sh"
      remote_src: yes
    become: true  
    ignore_errors: true  
  - name: Copy stderr log to home directory in Bootstrap VM
    ansible.builtin.copy:
      src: /var/lib/waagent/custom-script/download/0/stderr
      dest: "/home/{{ ansible_ssh_user }}/stderr"
      remote_src: yes
    become: true
    ignore_errors: true   
  - name: Copy stdout log to home directory in Bootstrap VM
    ansible.builtin.copy:
      src: /var/lib/waagent/custom-script/download/0/stdout
      dest: "/home/{{ ansible_ssh_user }}/stdout"
      remote_src: yes
    become: true
    ignore_errors: true                      
  - name: Create an archive of the logs captured in Bootstrap VM
    community.general.archive:
      path:
      - ~/openshift_install.log
      - ~/handler.log
      - ~/bootstrap.sh
      - ~/stderr
      - ~/stdout
      dest: "~/zmodstack-deploy-logs-{{ date_time_stamp }}.tar.bz2"
      format: bz2
      remove: true
  - name: Fetch log archive from Bootstrap VM to local system
    ansible.builtin.fetch:
      src: "~/zmodstack-deploy-logs-{{ date_time_stamp }}.tar.bz2"
      dest: "{{ logs_dir }}/zmodstack-deploy-logs-{{ date_time_stamp }}.tar.bz2"
      flat: yes
  - name: Prints folder in local system where logs are copied
    ansible.builtin.debug:
      msg: "Logs are copied in {{ logs_dir }}. Logs may contain sensitive information, so please check and remove those before sending across."
