region: us-east-1
aws_regions:
  us-east-1:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    # us-east-1e does not support m5.large instance types!
    - us-east-1e
    - us-east-1f
  us-east-2:
    - us-east-2a
    - us-east-2b
    - us-east-2c
  us-west-1:
    - us-west-1a
    - us-west-1b
  us-west-2:
    - us-west-2a
    - us-west-2b
    - us-west-2c
    - us-west-2d
  eu-west-2:
    - eu-west-2a
    - eu-west-2b
    - eu-west-2c