---
schemaVersion: 2.2.0
metadata:
  name: wazi-devspaces
attributes:
  controller.devfile.io/devworkspace-config:
    name: devworkspace-config
    namespace: openshift-operators
  controller.devfile.io/storage-type: per-user
projects:
  - git:
      remotes:
        origin: https://github.com/cicsdev/cics-banking-sample-application-cbsa.git
    name: cbsa
components:
  - attributes:
      controller.devfile.io/merge-contribution: true
    container:
      endpoints:
        - attributes:
            cookiesAuthEnabled: false
          exposure: public
          name: analyze-api
          protocol: https
          targetPort: 4680
        - attributes:
            cookiesAuthEnabled: false
          exposure: public
          name: analyze-ui
          protocol: https
          targetPort: 5000
        - attributes:
            cookiesAuthEnabled: false
          exposure: none
          name: analyze-weasy1
          protocol: http
          targetPort: 4080
        - attributes:
            cookiesAuthEnabled: false
          exposure: none
          name: analyze-weasy2
          protocol: http
          targetPort: 4081
        - attributes:
            cookiesAuthEnabled: false
          exposure: none
          name: analyze-swagger
          protocol: http
          targetPort: 8000
      env:
        - name: CHE_DASHBOARD_URL
          value: https://eclipse-che.wazi-ocp413-jp-tok-d10d2b22b9cba0d96e58c384c941a14d-0000.jp-tok.containers.appdomain.cloud
        - name: CHE_PLUGIN_REGISTRY_URL
          value: https://eclipse-che.wazi-ocp413-jp-tok-d10d2b22b9cba0d96e58c384c941a14d-0000.jp-tok.containers.appdomain.cloud/plugin-registry/v3
        - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
          value: http://plugin-registry.openshift-operators.svc:8080/v3
        - name: CLUSTER_CONSOLE_URL
          value: https://console-openshift-console.wazi-ocp413-jp-tok-d10d2b22b9cba0d96e58c384c941a14d-0000.jp-tok.containers.appdomain.cloud
        - name: CLUSTER_CONSOLE_TITLE
          value: OpenShift console
        - name: OPENVSX_REGISTRY_URL
          value: ''
        - name: WAZI_LICENSE_USAGE
          value: wazi
      image: icr.io/wazi-code/ibm-wazi-for-devspaces-sidecar@sha256:6832c15f01f91af86cc5824ce2cc6bf3530b1408c5e53da86ef344ae34932d55
      memoryLimit: 3072Mi
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
        - name: data
          path: /home/user/wazianalyze/data
    name: wazi
  - container:
      endpoints:
        - exposure: public
          name: zosconnect-ui
          path: /zosConnect/designer/
          protocol: http
          targetPort: 9080
      env:
        - name: ZCON_DESIGNER_PROJECT
          value: /projects/cbsa/etc/install/base/zosconnectserver
      image: icr.io/zosconnect/ibm-zcon-designer:3.0.73
      memoryLimit: 4927M
      mountSources: true
      sourceMapping: /projects
    name: zosconnect
  - name: zowe
    volume:
      size: 100Mi
  - name: data
    volume:
      size: 1024Mi
