apiVersion: v1
baseDomain: 
compute:
- name: worker
  hyperthreading: Enabled
  replicas: 0
controlPlane:
  name: master
  replicas: 1
  architecture: amd64
  hyperthreading: Enabled
  platform:
    aws:
      type: m6a.2xlarge
      rootVolume:
        size: 150
        type: gp3
metadata:
  name: test-sno-dec5
platform:
  aws:
    region: us-west-1
    userTags:
      owner: "zsw"
      type: "sno"
      usage: "Dev"
      description: "Product Development and Demo environment for OpenShift"
pullSecret: ''
sshKey: ''
