#jinja2: trim_blocks:False
apiVersion: v1
baseDomain: {{ base_domain }}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - {{ availability_zone1 }}
      type: {{ control_plane_node_instance_type }}
      rootVolume:
        size: {{ control_plane_node_instance_volume_size }}
        type: {{ control_plane_node_instance_volume_type }}
      replicas: 1
metadata:
  name: {{ cluster_name }}
networking:
  clusterNetwork:
  - cidr: {{ cluster_network_cidr }}
    hostPrefix: {{ cluster_network_host_prefix }}
  machineNetwork:
  - cidr: {{ machine_network_cidr }}
    networkType: OpenShiftSDN
  serviceNetwork:
  - {{ service_network_cidr }}
platform:
  aws:
    region: {{ region }}
    subnets:
    - {{ control_plane_node_subnet1_id }}
    - {{ computenode_subnet1_id }}
    userTags:
      "zmodstack:provisioner": openshift-install
      "zmodstack:cfn-stack-name": {{ cluster_name }}
publish: "External"
pullSecret: '{{ lookup('file', '{{ playbook_dir }}/pull-secret') }}'
sshKey: {{ public_ssh_key }}
fips: {{ enable_fips }}
