---
# vars file for wazi-aas
os_type: zos
name_prefix: "zmodstack-deploy"
instance:
  name: "{{ name_prefix }}-zos-vsi"
  profile: mz2o-2x16
  image: ibm-zos.*
  username: IBMUSER
  python_interpreters:
    - /usr/lpp/IBM/cyp/v3r9/pyz/bin/python3
    - /usr/lpp/IBM/cyp/v3r8/pyz/bin/python3
ssh_key_name: zmodstack-deploy
ssh_public_key: "{{lookup('file', '~/.ssh/zmodstack-deploy.pub') }}"
region: "eu-gb"
zone: "{{region}}-1"
cache_vsi: false
resource_group_name: "zmodstack-deploy"
total_ipv4_address_count: 256