---
# vars file for wazi-aas
os_type: zos
name_prefix: "ivan-vsi-fix"
primary_network_interface_name: "eth0"
instance:
  name: "{{ name_prefix }}-zos-vsi"
  profile: mz2o-2x16
  # image: adcd*
  # image: ibm-zos.*
  image: adcdsysparmnv*
  username: IBMUSER
  python_interpreters:
    - /usr/lpp/IBM/cyp/pyz/bin/python3
    - /usr/lpp/IBM/cyp/v3r9/pyz/bin/python3
    - /usr/lpp/IBM/cyp/v3r8/pyz/bin/python3
ssh_key_name: zmodstack-deploy
ssh_public_key: "{{lookup('file', '~/.ssh/zmodstack-deploy.pub') }}"
ssh_public_path: "~/.ssh/zmodstack-deploy.pub"
# Need to point to a file locally with the password if running locally
ssh_password: "{{lookup('file', '/workspace/ws/password') }}"
# Need to point to a file locally with the password if running locally
ssh_password_file: "/workspace/ws/password"
# region: eu-gb
region: us-east
zone: "{{region}}-2"
cache_vsi: false
resource_group_name: "zmodstack-deploy"
total_ipv4_address_count: 256

# New variables for data volume
data_volume_name: "{{ name_prefix }}-data"
data_volume_profile: "general-purpose"
data_volume_capacity: 250  # Set the desired storage size in GB
data_volume_snapshot: "{{ instance.image }}"
delete_volume_on_instance_delete: true
data_volume_iops: 1000
num_subnets: 3
# Need to point to a file locally if running locally
path_workspace: "/workspace/ws"