---
# vars file for wazi-aas
os_type: zos
name_prefix: "zmodstack-deploy-demo"
instance:
  name: "{{ name_prefix }}-zos-vsi"
  profile: mz2o-2x16
  image: adcd*
  # image: ibm-zos.*
  username: IBMUSER
  python_interpreters:
    - /usr/lpp/IBM/cyp/v3r9/pyz/bin/python3
    - /usr/lpp/IBM/cyp/v3r8/pyz/bin/python3
ssh_key_name: zmodstack-deploy
ssh_public_key: "{{lookup('file', '~/.ssh/zmodstack-deploy.pub') }}"
region: eu-gb
# region: us-east
zone: "{{region}}-1"
cache_vsi: false
resource_group_name: "zmodstack-deploy"
total_ipv4_address_count: 256

# New variables for data volume
data_volume_name: "zmodstack-deploy-dv"
data_volume_profile: "general-purpose"
data_volume_capacity: 336  # Set the desired storage size in GB
data_volume_snapshot: ".*data$"
delete_volume_on_instance_delete: true
data_volume_iops: 3000

path_workspace: "/Users/izzymusa/repos/zmodstack-deploy/ocp/ansible"