apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: debug
spec:
  params:
    - name: directory
      type: string
  steps:
    - image: registry.redhat.io/ubi8/ubi-minimal
      name: list-directory
      resources: {}
      script: |
        #!/usr/bin/env sh
        set -ex

        ls -l $(workspaces.dir.path)
  workspaces:
    - description: A directory to mount as a workspace
      name: dir
