apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: debug
spec:
  params:
    - name: image
      type: string
      description: The image to launch for debugging
      default: icr.io/zmodstack/deploy/tekton-ansible:latest
    - name: command
      description: A command to run within the debug Pod, defaults to sleep to allow user to open a Pod terminal
      type: string
      default: sleep 6000
  steps:
    - image: $(params.image)
      name: run-command
      resources: {}
      script: |
        #!/usr/bin/env sh
        set -ex
        $(params.command)
  workspaces:
    - description: A directory to mount as a workspace
      name: ws
