---
- name: Deploy OCP Cluster
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Deployment
      ansible.builtin.include_role:
        name: ocpcluster
      tags: ocpcluster
    - name: Auto Scaler
      ansible.builtin.include_role:
        name: autoscaler
      when: enable_autoscaler | bool
      tags: autoscaler
