---
- name: Deploy OCP Cluster
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Deployment
      ansible.builtin.include_role:
        name: ocpcluster
      tags: ocpcluster
