---
- name: Pre Deploy Installations
  hosts: localhost
  become: true
  gather_facts: false
  
  collections:
  - kubernetes.core
  - cloud.common

  tasks:
  - name: Update Packages and Installing Package Dependencies
    ansible.builtin.dnf:
      name: "*"
      state: latest
  - name: Import a key from a url
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc
  - name: Install the packages-microsoft-prod rpm from a remote repo
    ansible.builtin.dnf:
      name: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm'
      state: present
  - name: Install the latest version of jq and Azure CLI
    ansible.builtin.dnf:
      name:
        - azure-cli
        - jq
      state: latest     
  - name: Install latest version of podman and httpd-tools
    ansible.builtin.yum:
      name:
        - podman
        - httpd-tools
      state: latest   
  - name: Install PyYAML
    ansible.builtin.pip:
      name: PyYAML
      extra_args: --ignore-installed
  - name: Install kubernetes and openshift
    ansible.builtin.pip:
      name:
        - kubernetes
        - openshift