---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: icr.io/cpopen/ibm-operator-catalog
  displayName: IBM Operator Catalog
  publisher: IBM
  updateStrategy:
    registryPoll:
      interval: 30m
