---
apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ CLUSTER_ID }}-health-check-compute-{{ LOCATION }}1
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: compute
      machine.openshift.io/cluster-api-machine-type: compute
      machine.openshift.io/cluster-api-machineset: {{ CLUSTER_ID }}-worker-{{ LOCATION }}1
  unhealthyConditions:
  - type:    "Ready"
    timeout: "300s"
    status: "False"
  - type:    "Ready"
    timeout: "300s"
    status: "Unknown"
  maxUnhealthy: "30%"
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ CLUSTER_ID }}-health-check-compute-{{ LOCATION }}2
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: compute
      machine.openshift.io/cluster-api-machine-type: compute
      machine.openshift.io/cluster-api-machineset: {{ CLUSTER_ID }}-worker-{{ LOCATION }}2
  unhealthyConditions:
  - type:    "Ready"
    timeout: "300s"
    status: "False"
  - type:    "Ready"
    timeout: "300s"
    status: "Unknown"
  maxUnhealthy: "30%"
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ CLUSTER_ID }}-health-check-compute-{{ LOCATION }}3
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: compute
      machine.openshift.io/cluster-api-machine-type: compute
      machine.openshift.io/cluster-api-machineset: {{ CLUSTER_ID }}-worker-{{ LOCATION }}3
  unhealthyConditions:
  - type:    "Ready"
    timeout: "300s"
    status: "False"
  - type:    "Ready"
    timeout: "300s"
    status: "Unknown"
  maxUnhealthy: "30%"