---
- include_vars: zoscb.yml

- name: Create the SSH Secret Credential for VSI
  kubernetes.core.k8s:
    state: present
    namespace: ibm-zmodstack-deploy
    template: templates/secret.yml.j2
  vars:
    secret: "{{ secret }}"

# - name: Create SSH Secret via API call
#   uri:
#     url: https://ibm-zoscb-ui-zoscloudbroker-ibm-zmodstack-deploy.apps.ivandov-oct13.ibmzsoftware.com/api/credentials
#     method: POST
#     body_format: json
#     body:
#       username: ibmuser
#       ssh_key: "{{ secret.ssh_key }}"
#       operatorcollection_name: "{{ operators.cics.name }}"
#       zosendpoint_names: "{{ zvsi_endpoint_name }}"
#   register: results

# - debug:
#     var: results