---
# - include_vars: zoscb.yml

# - name: Create the SSH Secret Credential for VSI
#   kubernetes.core.k8s:
#     state: present
#     namespace: ibm-zmodstack-cloudbroker
#     template: templates/secret.yml.j2
#   vars:
#     secret: "{{ secret }}"