- include_vars: zoscb.yml

- name: Map the CICS Operator Collection
  kubernetes.core.k8s:
    state: present
    namespace: ibm-zmodstack-cloudbroker
    template: templates/suboperatorconfig.yml.j2
  vars:
    # TODO - replace with value from zvsi provisioning
    # oc_name: zos-cics-ts-operator.ibm.1.0.0
    # oc_url: https://galaxy.ansible.com/download/ibm-zos_cics_operator-1.0.0.tar.gz
    oc: "{{ operators.cics }}"
  register: mapped_suboperator
  until: mapped_suboperator.status.phase == Successful
  failed_when: mapped_suboperator.status.phase == Failed
  retries: 5
  delay: 30

- name: Print SOC value
  ansible.builtin.debug:
    var: mapped_suboperator