- name: Apply a ZosEndpoint configuration with zos-vsi connection details
  kubernetes.core.k8s:
    state: present
    namespace: ibm-zmodstack-cloudbroker
    template: 'templates/zosendpoint.yml.j2'
  vars:
    # TODO - replace with value from zvsi provisioning
    zvsi_host: 52.116.124.125
    zvsi_ssh_port: 22
