---
################################################################################
# Copyright (c) IBM Corporation 2021
################################################################################

################################################################################
# Description of the properties used in this configuration:
# - Property `PYZ` is the python installation home path on the z/OS managed node (target),
#    e.g, pyz: "/usr/lpp/IBM/cyp/v3r8/pyz"
# - Property `ZOAU` is the ZOAU installation home on the z/OS managed node (target),
#    e.g, zoau: "/usr/lpp/IBM/zoautil"
# - property `ansible_python_interpreter` is the z/OS managed node (target) Python
#    binary installation path, e.g, ansible_python_interpreter: "{{PYZ}}/bin/python3"
#
# Note, PYZ and ZOAU environment variables must be configured.
################################################################################

# Uncomment below line for Python path for a WaaS ADCD instance
PYZ: "/usr/lpp/IBM/cyp/pyz"
# Uncomment below line for Python path for a WaaS Stock instance
# PYZ: "/usr/lpp/IBM/cyp/v3r11/pyz" 
ZOAU: "/usr/lpp/IBM/zoautil"

################################################################################
# Do not configure, variable substituion will correctly set the
# variable`ansible_python_interpreter`
################################################################################
ansible_python_interpreter: "{{ PYZ }}/bin/python3"
