###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    keyring: 'ZCONNECT'
    owner_id: 'ZOSCSRV'
    cn: 'ZOSCSRV_ZCONN_Server'
    o: 'IBM'    
    ou: 'ZOSVSI'
    country: 'US'
    cert_label: 'ZCONN_Server'
    sign_label: 'ADCD_COMMON'
    expiry_date: '2024-11-30'

  tasks:
    - include_role:
        name: issue_racf_cmd
      vars:
        task_description: 'Create a new keyring'
        command:
          - RACDCERT ADDRING({{keyring}}) ID({{owner_id}})
          - RACDCERT LISTRING({{keyring}}) ID({{owner_id}})

    - include_role:
        name: issue_racf_cmd
      vars:
        task_description: 'Create new local-CA-signed USER cert and connect to keyring'
        command:
          - >
            RACDCERT GENCERT ID({{owner_id}}) SUBJECTSDN(CN('{{cn}}') +
              O('{{o}}') OU('{{ou}}') C('{{country}}')) WITHLABEL('{{cert_label}}') +
              SIGNWITH(CERTAUTH LABEL('{{sign_label}}')) +
              NOTAFTER(DATE({{expiry_date}}))
          - >
            RACDCERT ID({{owner_id}}) CONNECT(LABEL('{{cert_label}}') +
              RING({{keyring}}) DEFAULT)
          - >
            RACDCERT LISTRING({{keyring}}) ID({{owner_id}})
          - >
            RACDCERT LISTCHAIN (LABEL('{{cert_label}}')) ID({{owner_id}})

    - include_role:
        name: issue_operator_cmd
      vars:
        task_description: 'Refresh keyring'
        command: "F {{owner_id}},REFRESH,KEYSTORE"
