###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    owner_id: 'ZOSCSRV'
    cert_label: 'ZCONN_Server'

  tasks:
    - include_role:
        name: issue_racf_cmd
      vars:
        task_description: 'Delete cert {{cert_label}}'
        command:
          - RACDCERT ID({{ owner_id}}) DELETE(LABEL('{{cert_label}}'))
          - RACDCERT ID({{ owner_id}}) LIST(LABEL('{{cert_label}}'))
