---
- name: "Install Red Hat OpenShift Pipelines"
  kubernetes.core.k8s:
    state: present
    src: "files/pipeline-subscription.yaml"

- name: "Verify Red Hat OpenShift Pipelines Operator is installed successfully"
  ansible.builtin.command: oc get tektonconfig config --kubeconfig ~/.kube/config
  register: pipelines_status
  changed_when: false
  until:
    - "'True' in pipelines_status.stdout"
  retries: 30
  delay: 30

- name: "Create project with Native YAML API for OCP Pipelines"
  kubernetes.core.k8s:
    state: present
    src: "files/pipeline-project.yaml"

- name: "Deploy Ansible Task"
  kubernetes.core.k8s:
    state: present
    namespace: "ibm-zmodstack-pipelines"
    src: "files/ansible.yaml"

- name: "Create Cluster Roles"
  kubernetes.core.k8s:
    state: present
    src: "files/cluster-roles.yaml"

- name: "Create Cluster Role Bindings"
  kubernetes.core.k8s:
    state: present
    src: "files/cluster-role-bindings.yaml"

- name: "Install OCP Pipeline for z/OS Cloud Broker"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ pipelines.namespace }}"
    src: "files/zoscb-install-pipeline.yaml"
