---
- name: Destroy Azure Resources
  hosts: localhost
  collections:
  - azure.azcollection
  
  vars:
    CLUSTER_RESOURCE_GROUP_DEV: z-mod-stack-dev-abc12-rg
    RESOURCE_GROUP_DEV: z-mod-stack-dev-rg

  tasks:  
  - name: Delete Resource Group for Cluster Resources
    azure_rm_resourcegroup:
      name: "{{ CLUSTER_RESOURCE_GROUP_DEV }}"
      force_delete_nonempty: yes
      state: absent        

  - name: Delete Resource Group for Bootstrap Resources
    azure_rm_resourcegroup:
      name: "{{ RESOURCE_GROUP_DEV }}"
      force_delete_nonempty: yes
      state: absent
