---
- name: Deploy ARM Template
  hosts: localhost
  collections:
  - azure.azcollection
  
  vars:
    RESOURCE_GROUP_DEV: z-mod-stack-dev-rg
    DEPLOYMENT_NAME: OCP-Cluster-Dev
    ARM_TEMPLATE: "{{ lookup('file', '../marketplace/mainTemplate.json') }}"
    ARM_PARAMETERS: "{{ (lookup('file', '../marketplace/mainParameters.json') | from_json).parameters }}"
    
  tasks:
  - name: Create a Resource Group for OCP Deployment
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{ RESOURCE_GROUP_DEV }}"
      location: "{{ LOCATION }}"

  - name: Create OCP Cluster
    azure.azcollection.azure_rm_deployment:
      name: "{{ DEPLOYMENT_NAME }}"
      resource_group_name: "{{ RESOURCE_GROUP_DEV }}"
      location: "{{ LOCATION }}"
      template: "{{ ARM_TEMPLATE }}"
      parameters: "{{ ARM_PARAMETERS }}"
