---
- name: Create OCP Cluster
  hosts: localhost

  vars:
    RESOURCE_GROUP_NAME: z-mod-stack-dev-rg
    LOCATION: eastus
    CLUSTER_RESOURCE_GROUP_NAME: z-mod-stack-ocp-dev-rg
    DEPLOYMENT_NAME: OCP-Cluster-Dev
    ARM_TEMPLATE: "{{ lookup('file', '../../../marketplace/mainTemplate.json') }}"
    ARM_PARAMETERS: "{{ (lookup('file', '../../../marketplace/mainParameters.json') | from_json).parameters }}"

  tasks:
    - name: Create a Resource Group for Deployment
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ RESOURCE_GROUP_NAME }}"
        location: "{{ LOCATION }}"

    - name: Create a Resource Group for OCP Cluster
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ CLUSTER_RESOURCE_GROUP_NAME }}"
        location: "{{ LOCATION }}"

    - name: Deploy OCP Cluster
      azure.azcollection.azure_rm_deployment:
        name: "{{ DEPLOYMENT_NAME }}"
        resource_group_name: "{{ RESOURCE_GROUP_NAME }}"
        location: "{{ LOCATION }}"
        template: "{{ ARM_TEMPLATE }}"
        parameters: "{{ ARM_PARAMETERS }}"
