---
- name: Delete OCP Cluster
  hosts: localhost

  vars:
    dns_resource_group_name: z-mod-stack-rg
    dns_zone: ibmzsw.com
    cluster_name: z-mod-stack-dev
    cluster_resource_group_name: z-mod-stack-ocp-dev
    resource_group_name: z-mod-stack-dev

  tasks:
    - name: Delete A Record from DNS Zone
      azure.azcollection.azure_rm_dnsrecordset:
        resource_group: "{{ dns_resource_group_name }}"
        record_type: A
        relative_name: "*.apps.{{ cluster_name }}"
        zone_name: "{{ dns_zone }}"
        state: absent

    - name: Delete CNAME Record from DNS Zone
      azure.azcollection.azure_rm_dnsrecordset:
        resource_group: "{{ dns_resource_group_name }}"
        record_type: CNAME
        relative_name: "api.{{ cluster_name }}"
        zone_name: "{{ dns_zone }}"
        state: absent

    - name: Delete Resource Group for OCP Cluster Resources
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ cluster_resource_group_name }}"
        force_delete_nonempty: true
        state: absent

    - name: Delete Resource Group for Bootstrap Resources
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        force_delete_nonempty: true
        state: absent
