name: AWS Deployment

on:
  push:
    paths:
      - '.github/workflows/aws-deploy.yml'
      - 'aws/**' 
      - 'ocp/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/aws-deploy.yml'
      - 'aws/**'
      - 'ocp/**'


env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ANSIBLE_PLAYBOOK_PROVISION: ./aws/ansible/deployment/playbooks/run-provision.yml
  ANSIBLE_PLAYBOOK_VALIDATE: ./aws/ansible/deployment/playbooks/run-validate.yml
  ANSIBLE_PLAYBOOK_DEPROVISION: ./aws/ansible/deployment/playbooks/run-deprovision.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name on push
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Extract branch name on pull request
      if: github.event_name == 'pull_request'
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

    - name: Print branch name
      run: echo 'The branch name is' $BRANCH_NAME
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Upload to S3 bucket
      run: |
        aws s3 cp ./aws/cloudformation/cluster.yml s3://z-mod-stack-aws-dev/branches/$BRANCH_NAME/cloudformation/cluster.yml
        aws s3 cp ./aws/cloudformation/vpc.yml s3://z-mod-stack-aws-dev/branches/$BRANCH_NAME/cloudformation/vpc.yml
        aws s3 cp ./aws/cloudformation/main.yml s3://z-mod-stack-aws-dev/branches/$BRANCH_NAME/cloudformation/main.yml  
   
    - name: 'AWS Configure'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Run Ansible Playbooks
      run: |
        ansible-galaxy collection install amazon.aws
        pip install 'ansible[aws]'
        pip install boto3 cfn-lint ansible-core
        stackname="git-${{ github.run_id }}"
        ansible-playbook ${{ env.ANSIBLE_PLAYBOOK_PROVISION }} --extra-vars "OCP_PASSWORD=${{ secrets.AWS_OCP_PASSWORD }} API_KEY=${{ secrets.API_KEY }} stack_name=$stackname region=${{ env.AWS_REGION }}"
        ansible-playbook ${{ env.ANSIBLE_PLAYBOOK_VALIDATE }} --extra-vars  "stack_name=$stackname OCP_PASSWORD=${{ secrets.AWS_OCP_PASSWORD }}"
        ansible-playbook ${{ env.ANSIBLE_PLAYBOOK_DEPROVISION }} --extra-vars  "stack_name=$stackname region=${{ env.AWS_REGION }}"
      shell: bash
