name: AWS Lint Checks

on:
  push:
    paths:
      - '.github/workflows/aws-test.yml'
      - 'aws/**'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print branch name
      run: echo 'The branch name is' $BRANCH_NAME
    
    - name: Checkout Repository
      uses: actions/checkout@v2
   
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install cfn-lint
      run: |
        pip3 install cfn-lint

    - name: Run cfn-lint
      run: |
        cfn-lint ./aws/cloudformation/cluster.yml
        cfn-lint ./aws/cloudformation/vpc.yml
        cfn-lint ./aws/cloudformation/main.yml

    - name: 'AWS Configure'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload to S3 bucket
      run: |
        aws s3 cp ./aws/cloudformation/cluster.yml s3://z-mod-stack-aws-dev/branches/$BRANCH_NAME/cloudformation/cluster.yml
        aws s3 cp ./aws/cloudformation/vpc.yml s3://z-mod-stack-aws-dev/branches/$BRANCH_NAME/cloudformation/vpc.yml
        aws s3 cp ./aws/cloudformation/main.yml s3://z-mod-stack-aws-dev/branches/$BRANCH_NAME/cloudformation/main.yml  
