name: Azure Deployment

on:
  push:
    paths:
      - '.github/workflows/azure-deploy.yml'
      - 'azure/**' 
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/azure-deploy.yml'
      - 'azure/**'

env:
  ARM_TEMPLATE_BICEP: ./azure/marketplace/mainTemplate.bicep
  ARM_TEMPLATE_JSON: ./azure/marketplace/mainTemplate.json
  ARM_TEMPLATE_BICEP_TO_JSON: ./azure/marketplace/mainTemplateBicepToJson.json
  WORK_DIR: ./azure/marketplace
  ANSIBLE_PLAYBOOK: ./azure/ansible/deployment/playbooks/run-provision.yml

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Create ARM Template in JSON from ARM Template in Bicep
      uses: Azure/bicep-build-action@v1.0.1
      with:
        bicepFilePath: ${{ env.ARM_TEMPLATE_BICEP }}
        outputFilePath: ${{ env.ARM_TEMPLATE_BICEP_TO_JSON }} 
    - name: Check mainTemplate.json is Latest
      run: diff ${{ env.ARM_TEMPLATE_JSON }} ${{ env.ARM_TEMPLATE_BICEP_TO_JSON }}
      shell: bash
      continue-on-error: true  
    - name: Run ARM-TTK
      uses: microsoft/action-armttk@v1
      with:
        workdir: ${{ env.WORK_DIR }} 
    - name: 'AZ CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Ansible Playbook Runner
      run: |
        ansible-galaxy collection install azure.azcollection --force
        pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
        pip install 'ansible[azure]'
        ansible-playbook ${{ env.ANSIBLE_PLAYBOOK }}
      shell: bash