name: Azure Deployment

on:
  push:
    paths:
      - '.github/workflows/azure-deploy.yml'
      - 'azure/**' 
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/azure-deploy.yml'
      - 'azure/**'

env:
  RESOURCE_GROUP_NAME: z-mod-stack-dev-rg
  RESOURCE_GROUP_LOCATION: eastus
  ARM_TEMPLATE: azure/marketplace/mainTemplate.json
  ARM_PARAMETERS: azure/marketplace/mainParameters.json

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 
    - name: Run ARM-TTK
      uses: microsoft/action-armttk@v1
      with:
        workdir: azure/marketplace/   
    - name: 'AZ CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Create Resource Group'
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
          echo "Azure Resource Group is created"    
    - name: 'Deploy OCP Cluster'
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ${{ env.ARM_TEMPLATE }}
        parameters: ${{ env.ARM_PARAMETERS }}
